name: Deploy Docsify site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Docsify CLI
      run: npm install -g docsify-cli

    - name: Initialize Docsify
      run: docsify init ./docs

    - name: Deploy to GitHub Pages
      run: |
        docsify serve docs
        echo "Docsify site deployed to GitHub Pages"